### ISSUE TITLE
Windows 10 build issues

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#322]
See https://github.com/docbook/xslTNG/commit/32a6950112d44f17f99a3ccea439b76eef68fef4, which gets past `path` being null so that the build fails later.

There's probably something more sensible that can be done by testing for the current OS.

**Comment by ndw** [comment]
Right. I'll try it on Windows.

**Comment by tgraham-antenna** [comment]
It doesn't get you much further. My next error is:

```
> Could not create task ':locale_C:\projects\other\xslTNG\src\main\locale\af.xml'.
   > The task name 'locale_C:\projects\other\xslTNG\src\main\locale\af.xml' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |].
```

and I have no idea how to fix that.

**Comment by ndw** [comment]
I've been down this road before. In fact, I thought I'd made this work on Windows. Anyway. I'll see if I can push all the fixes necessary this evening.

**Comment by tgraham-antenna** [comment]
I've given up on Windows and am trying Linux Mint 21.1 in a VM. See #323.

**Comment by tgraham-antenna** [comment]
Understandable. Emacs and Cygwin are the only things that make Windows remotely bearable, and they're no help here.

**Comment by tgraham-antenna** [comment]
Thanks, and it's sad that it took that much effort.

**Comment by ndw** [comment]
I'd be curious to know if it works for you. The [expletive, expletive, expletive] thing will not work in GitHub actions. Some weird [expletive] encoding issue in `xspec.bat` formatting the report.

**Comment by tgraham-antenna** [comment]
I haven't got past the 'compileSASS' step: SASS installed by `npm` failed to run for node != Dart reasons, and the Windows download of SASS is a batch file that runs in a command prompt shell but won't run from the Gradle task.

Currently upgrading node.js to see if I can reinstall the `npm` SASS and have it work, but upgrading is taking forever (and has already installed a second Python 3 to add to the one that I previously installed because of xslTNG).

**Comment by ndw** [comment]
Ugh. Sorry. Maybe I should commit the CSS files so that SASS is an optional dependency.

FWIW, `choco install sass` seems to have done the trick for me.

**Comment by tgraham-antenna** [comment]
If it's going to be any consolation, I get:
```
> Task :a11y.xspec
Creating Test Stylesheet...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
```

`choco install sass` installed an executable, so that worked.

Had to install `click` and `Pygmentize` for the new Python 3, but now I fail similarly to how you do, though at a different index.

**Comment by tgraham-antenna** [comment]
BTW, you might as well keep SASS as a dependency: if someone is going to hack the CSS to the point of submitting a PR, you are going to much prefer that the PR is against the SASS and not the output CSS.

**Comment by ndw** [comment]
Do you get different/better results if you set `JAVA_TOOL_OPTIONS` to `-Dfile.encoding=utf-8` in the environment?

**Comment by tgraham-antenna** [comment]
It picked up the setting and failed in exactly the same way.

I tried adding `cmd /c` to the start of the XSpec command lines, but that didn't change anything, not even the error message:
```
Process 'command 'C:\projects\other\xslTNG\build/xspec-2.2.4/bin/xspec.bat'' finished with non-zero exit value 1
```

**Comment by tgraham-antenna** [comment]
Naturally, my stack trace is very different from yours:
```
> Task :zipStagePygments
Without pygmentize, zip file resources will be incomplete.

> Task :a11y.xspec
Creating Test Stylesheet...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at net.sf.saxon.trans.CommandLineOptions.setActualOptions(CommandLineOptions.java:136)
        at net.sf.saxon.Transform.doTransform(Transform.java:293)
        at net.sf.saxon.Transform.main(Transform.java:81)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=utf-8

*** Error compiling the test suite

> Task :a11y.xspec FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':a11y.xspec'.
> Process 'command 'C:\projects\other\xslTNG\build/xspec-2.2.4/bin/xspec.bat'' finished with non-zero exit value 1

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':a11y.xspec'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
...
```

**Comment by ndw** [comment]
Ah.I figured that one out. Pull the latest. The `xspec.bat` file included `"%CLASSPATH%"` where `%CLASSPATH%` was required. The extra quotes mean that a zero length string gets passed to Saxon as a command line argument and that all goes horribly wrong.

**Comment by tgraham-antenna** [comment]
Sorry, no, still fails the same way for me.

And what happens when someone has a space character in their classpath?

**Comment by ndw** [comment]
It's not the space character that's the problem, it's the literal emtpy string sent as a command line option. Saxon clumsily looks to see if the first character is "-" and falls over. I've patched that, but I'm surprised the latest didn't fix...oh, wait. Run `clean`. The XSpec stuff is only installed if it isn't already installed.

**Comment by ndw** [comment]
Sorry. I wrote `%CLASSPATH%`, I mean `%CATALOG%`. #facepalm

**Comment by tgraham-antenna** [comment]
I was wondering why I only saw `%CATALOG%` in the diffs on GitHub.

**Comment by tgraham-antenna** [comment]
Consistently failed to find `pygmentize` on Windows, so I applied a bit of brute strength:
```
  path.split(OperatingSystem.current().isWindows() ? ';+' : ':+').each { segment ->
    if (script == null) {
      println("${segment}")
      def testfile = new File("${segment}/pygmentize.exe")
```

I currently have `python`, not `python3`, so I had to brute-strength that, too.

**Comment by ndw** [comment]
I couldn't get Pygmentize on Windows either. I managed to make the build succeed without it.

`choco install python3` might fix the python problem.

**Comment by tgraham-antenna** [comment]
That 'fix' lets gradle find `pygmentize`:
```
Using Pygments from C:\Python310\Scripts\pygmentize.exe
```

Inducing gradle to find `pygmentize` let `dist` finish without error.

I have more Pythons than I know what to do with: updating `npm` on Windows installs/updates both Chocolatey and Python, plus I have the Python app from the Microsoft store on one machine.

**Comment by tgraham-antenna** [comment]
I have a different Windows machine that fails with:

```
> Task :locale_af.xml FAILED
Error
   I/O error reported by XML parser processing
  file:///C:/Projects/other/xslTNG/src/main/xslt/modules/xform-locale.xsl. Caused by
  java.io.FileNotFoundException:
  C:\Projects\other\xslTNG\src\main\xslt\modules\xform-locale.xsl (The system cannot find
  the path specified)
I/O error reported by XML parser processing file:///C:/.../xslTNG/src/main/xslt/modules/xform-locale.xsl

FAILURE: Build failed with an exception.
```

`xform-locale.xsl` does exist and has not been modified.

**Comment by ndw** [comment]
The number and variety of ways that Windows can fail is...remarkable. I have a second Windows machine around somewhere and a VM on an Intel MacBook. I can try those, I guess.

**Comment by ndw** [comment]
I think this is fixed now. There was a depedency on an old version of Xerces being pulled in transitively.

**Comment by tgraham-antenna** [comment]
Still getting that `Task :locale_af.xml FAILED` error, and still no idea why.

I had to reinstate my searching for `pygmentize.exe` to get rid of the message about not finding `pygmentize`.

I have two other working systems -- one Windows, one Linux -- so getting the third system to work is not my priority right now.

**Comment by tgraham-antenna** [comment]
Who is their right mind has disks as separate silos?

Sorry, but I just realised that the missing file is because its on the E: drive, not the C: drive, and I'd fixated on the rest of the path after the drive letter.

Got further after copying my `xslTNG` to C:. Still had to add the `.exe` to find `pygmentize`. Now in some bizarre universe where Gradle trying to run python gets me messages about the Microsoft App Store.
